#!/bin/bash

# ШАГ 1.1: Проверить статус Docker Compose на сервере
echo "=== ШАГ 1.1: ПРОВЕРКА СТАТУСА DOCKER COMPOSE ==="
echo ""
echo "Команды для выполнения на сервере 46.8.255.137:"
echo ""
echo "# 1. Подключиться к серверу"
echo "ssh root@46.8.255.137"
echo ""
echo "# 2. Перейти в директорию проекта"
echo "cd /opt/sergeev-100"
echo ""
echo "# 3. Проверить Docker Compose статус"
echo "docker-compose -f docker-compose.moscow.yml ps"
echo ""
echo "# 4. Проверить все контейнеры"
echo "docker ps"
echo ""
echo "# 5. Проверить использование портов"
echo "netstat -tlnp | grep LISTEN"
echo ""
echo "# 6. Остановить Docker Compose (для миграции на K8s)"
echo "docker-compose -f docker-compose.moscow.yml down"
echo ""
echo "# 7. Проверить, что все остановлено"
echo "docker ps"
echo ""
echo "=== ОЖИДАЕМЫЙ РЕЗУЛЬТАТ ==="
echo "✅ Все контейнеры остановлены"
echo "✅ Порты свободны"
echo "✅ Готово к установке K3s"
